const shoes = [
  {
    title: "AHTOUNDRUN SHOES",
    price: "6,299.50",
    mrp: "8,999",
    discount: "-30%",
    category: "Men Running",
    color: "3 colours",
    imageUrl: "/src/assets/shoe_1.png",
    hoverImageUrl: "/src/assets/shoe_1_vertical.png",
  },
  {
    title: "SUPERSTAR SHOES",
    price: "6,299.50",
    mrp: "8,999",
    discount: "-30%",
    category: "Men Running",
    color: "3 colours",
    imageUrl: "/src/assets/shoe_2.png",
    hoverImageUrl: "/src/assets/shoe_2_vertical.png",
  },
  {
    title: "AHTOUNDRUN SHOES",
    price: "1,899.50",
    mrp: "3,799",
    discount: "-50%",
    category: "Men Running",
    color: "3 colours",
    imageUrl: "/src/assets/shoe_3.png",
    hoverImageUrl: "/src/assets/shoe_3_vertical.png",
  },
  {
    title: "AHTOUNDRUN SHOES",
    price: "1,899.50",
    mrp: "3,799",
    discount: "-50%",
    category: "Men Running",
    color: "3 colours",
    imageUrl: "/src/assets/shoe_4.png",
    hoverImageUrl: "/src/assets/shoe_4_vertical.png",
  },
  {
    title: "SUPERSTAR SHOES",
    price: "6,299.50",
    mrp: "8,999",
    discount: "-30%",
    category: "Men Running",
    color: "3 colours",
    imageUrl: "/src/assets/shoe_5.png",
    hoverImageUrl: "/src/assets/shoe_5_vertical.png",
  },
  {
    title: "SUPERSTAR SHOES",
    price: "1,899.50",
    mrp: "3,799",
    discount: "-50%",
    category: "Men Running",
    color: "3 colours",
    imageUrl: "/src/assets/shoe_1.png",
    hoverImageUrl: "/src/assets/shoe_1_vertical.png",
  },
  {
    title: "AHTOUNDRUN SHOES",
    price: "9,499.50",
    mrp: "18,999",
    discount: "-50%",
    category: "Men Running",
    color: "3 colours",
    imageUrl: "/src/assets/shoe_2.png",
    hoverImageUrl: "/src/assets/shoe_2_vertical.png",
  },
  {
    title: "SUPERSTAR SHOES",
    price: "1,649.50",
    mrp: "3,299",
    discount: "-50%",
    category: "Men Running",
    color: "3 colours",
    imageUrl: "/src/assets/shoe_3.png",
    hoverImageUrl: "/src/assets/shoe_3_vertical.png",
  },
];

export default shoes;
